### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by MichelDiz** [eemebarbe/schemeBeam#1]
No success to tryout this ripo.

**Comment by eemebarbe** [comment]
What sort of issue are you having?

**Comment by MichelDiz** [comment]
For test effect I tried to run directly by just skipping steps 4 and 5.
Is the steps strictly required?

Webpack worked

```
Version: webpack 1.15.0
Time: 10046ms
     Asset       Size  Chunks             Chunk Names
 bundle.js     446 kB    0, 1  [emitted]  index
vendors.js  757 bytes       1  [emitted]  vendors
 [254] ./config/settingsconfig.js 1.58 kB {0} [built]
    + 317 hidden modules
Done in 10.86s.
```

```js
yarn start
yarn start v0.27.5
$ node app.js
express-session deprecated undefined resave option; provide resave option authentication/auth.js:10:13
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option authentication/auth.js:10:13
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1298:19)
    at listenInCluster (net.js:1363:12)
    at Server.listen (net.js:1463:7)
    at Function.listen (/Volumes///////lib/application.js:618:24)
    at Object.<anonymous> (/Volumes/////app.js:35:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
error Command failed with exit code 1.
```

**Comment by eemebarbe** [comment]
You definitely can't skip step 3, that's what installs the app's dependencies. You don't need to complete step 4 to run the app.

**Comment by MichelDiz** [comment]
oh! sorry, was step 4 and 5 in my sentence. My mistake.

**Comment by eemebarbe** [comment]
Try running on a different port (above 1024)

**Comment by MichelDiz** [comment]
It worked. Thanks!

I do not know if it's purposeful but its package.json is "main": "index.js" instead of "app.js" and it does not have friendly scripts for yarn. Like : "start": "node app.js"

Best Reggards.

**Comment by eemebarbe** [comment]
Thanks for pointing that out. I'm inexperienced with yarn, I'll look into it. Glad it's working for you, I hope you can find some use out of it.
