### ISSUE TITLE
Node stops with error

### ISSUE THREAD

**Issue by CryptorClub** [eemebarbe/schemeBeam#16]
Every time got this error after ~10 hours of work. In one of files missed db connection as I understand. 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/root/schemeBeam/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/root/schemeBeam/node_modules/mysql/lib/Connection.js:97:28)
    at Socket.<anonymous> (/root/schemeBeam/node_modules/mysql/lib/Connection.js:502:10)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Do you have any ideas?

**Comment by CryptorClub** [comment]
Its Nginx auto started at background.
This should fix it:
`sudo update-rc.d -f nginx disable`
