### ISSUE TITLE
Show stats as soon as user is verified

### ISSUE THREAD

**Issue by elie222** [eemebarbe/schemeBeam#6]
It would be nice to show the user the stats as soon as he's verified.

It was a little unintuitive to me what was going on after I referred someone.

I will probably start working on this myself to fix it up. I finally got it running on Heroku just now.

**Comment by eemebarbe** [comment]
That makes sense. I kept it fairly minimal, leaving the copy up to the end user of the project. Glad to see you have it running. Hopefully I can help you out in the future, let me know what you're working on so we don't double up on efforts.

**Comment by elie222** [comment]
Hey,

So got it up and running on Heroku but it would then randomly crash and
didn't have the time to look into it. We decided to use Gleam instead.

We did start to move things out into env vars, but we made this change in a
private clone of this repo. I'll look to merge these changes into the main
repo again and make a PR.

**Comment by eemebarbe** [comment]
Do you have any logs for the crash?

**Comment by elie222** [comment]
https://crypto-warriors-invite.herokuapp.com/

```
2017-12-18T22:00:10.083899+00:00 app[web.1]: npm ERR! errno 1
2017-12-18T22:00:10.086706+00:00 app[web.1]: npm ERR! schemebeam@1.0.0 start: `node app.js`
2017-12-18T22:00:10.086888+00:00 app[web.1]: npm ERR! Exit status 1
2017-12-18T22:00:10.087158+00:00 app[web.1]: npm ERR! 
2017-12-18T22:00:10.087415+00:00 app[web.1]: npm ERR! Failed at the schemebeam@1.0.0 start script.
2017-12-18T22:00:10.087586+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-12-18T22:00:10.094780+00:00 app[web.1]: 
2017-12-18T22:00:10.095064+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-12-18T22:00:10.095254+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-12-18T22_00_10_089Z-debug.log
2017-12-18T22:00:10.257717+00:00 heroku[web.1]: State changed from up to crashed
2017-12-18T22:00:10.244779+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by elie222** [comment]
Just did a restart and it's back up. But pretty easy to crash it, by playing with it.

**Comment by elie222** [comment]
Also, I get this on startup:
```
 Mon, 18 Dec 2017 22:09:51 GMT express-session deprecated undefined resave option; provide resave option at authentication/auth.js:10:13
2017-12-18T22:09:51.685546+00:00 app[web.1]: Mon, 18 Dec 2017 22:09:51 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at authentication/auth.js:10:13
2017-12-18T22:09:51.685681+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2017-12-18T22:09:51.685683+00:00 app[web.1]: designed for a production environment, as it will leak
2017-12-18T22:09:51.685683+00:00 app[web.1]: memory, and will not scale past a single process.
2017-12-18T22:09:51.688416+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2017-12-18T22:09:51.688417+00:00 app[web.1]: designed for a production environment, as it will leak
2017-12-18T22:09:51.688418+00:00 app[web.1]: memory, and will not scale past a single process.
2017-12-18T22:09:51.697208+00:00 app[web.1]: schemeBeam up and running on port 3305
2017-12-18T22:09:52.624829+00:00 heroku[web.1]: State changed from starting to up
```

**Comment by eemebarbe** [comment]
hmm ok, I never had such issues in the past. thanks for pointing it out, I'll take a look.
